# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'fontingAwesome' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  pod 'FontAwesomeKit', '~> 2.2.0'
  pod 'CWStatusBarNotification', '~> 2.3.4'
  # use_frameworks!

  # Pods for fontingAwesome

  #target 'fontingAwesomeTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

  #target 'fontingAwesomeUITests' do
    #inherit! :search_paths
    # Pods for testing
  #end

end
